import '../models/Iitems/item_model.dart';

final List<Item> sampleItems = [
  Item(
    name: 'Classic Burger',
    stockCount: 25,
    category: 'Foods',
    description: 'A burger with lettuce, tomato, and cheese.',
    createdAt: DateTime.now().subtract(Duration(days: 3)),
    updatedAt: DateTime.now().subtract(Duration(days: 1)),
  ),
  Item(
    name: 'Cheeseburger',
    stockCount: 30,
    category: 'Foods',
    description: 'A burger topped with melted cheese.',
    createdAt: DateTime.now().subtract(Duration(days: 6)),
    updatedAt: DateTime.now().subtract(Duration(days: 2)),
  ),
  Item(
    name: 'Chicken Burger',
    stockCount: 15,
    category: 'Foods',
    description: 'A burger with a crispy chicken patty.',
    createdAt: DateTime.now().subtract(Duration(days: 7)),
    updatedAt: DateTime.now().subtract(Duration(days: 4)),
  ),
  Item(
    name: 'Veggie Burger',
    stockCount: 10,
    category: 'Foods',
    description: 'A vegetarian burger patty with fresh veggies.',
    createdAt: DateTime.now().subtract(Duration(days: 10)),
    updatedAt: DateTime.now().subtract(Duration(days: 7)),
  ),
  Item(
    name: 'Cola Classic',
    stockCount: 50,
    category: 'Beverages',
    description: 'The classic cola flavor.',
    createdAt: DateTime.now().subtract(Duration(days: 2)),
    updatedAt: DateTime.now().subtract(Duration(days: 2)),
  ),
  Item(
    name: 'Diet Cola',
    stockCount: 35,
    category: 'Beverages',
    description: 'Cola with zero sugar.',
    createdAt: DateTime.now().subtract(Duration(days: 8)),
    updatedAt: DateTime.now().subtract(Duration(days: 5)),
  ),
  Item(
    name: 'Vanilla Ice Cream',
    stockCount: 20,
    category: 'Desserts',
    description: 'Creamy vanilla flavored ice cream.',
    createdAt: DateTime.now().subtract(Duration(days: 5)),
    updatedAt: DateTime.now().subtract(Duration(days: 4)),
  ),
  Item(
    name: 'Chocolate Ice Cream',
    stockCount: 18,
    category: 'Desserts',
    description: 'Rich chocolate flavored ice cream.',
    createdAt: DateTime.now().subtract(Duration(days: 12)),
    updatedAt: DateTime.now().subtract(Duration(days: 6)),
  ),
  Item(
    name: 'Strawberry Ice Cream',
    stockCount: 15,
    category: 'Desserts',
    description: 'Sweet strawberry flavored ice cream.',
    createdAt: DateTime.now().subtract(Duration(days: 15)),
    updatedAt: DateTime.now().subtract(Duration(days: 12)),
  ),
    Item(
    name: 'Classic Burger',
    stockCount: 25,
    category: 'Foods',
    description: 'A burger with lettuce, tomato, and cheese.',
    createdAt: DateTime.now().subtract(Duration(days: 3)),
    updatedAt: DateTime.now().subtract(Duration(days: 1)),
  ),
  Item(
    name: 'Cheeseburger',
    stockCount: 30,
    category: 'Foods',
    description: 'A burger topped with melted cheese.',
    createdAt: DateTime.now().subtract(Duration(days: 6)),
    updatedAt: DateTime.now().subtract(Duration(days: 2)),
  ),
  Item(
    name: 'Chicken Burger',
    stockCount: 15,
    category: 'Foods',
    description: 'A burger with a crispy chicken patty.',
    createdAt: DateTime.now().subtract(Duration(days: 7)),
    updatedAt: DateTime.now().subtract(Duration(days: 4)),
  ),
  Item(
    name: 'Veggie Burger',
    stockCount: 10,
    category: 'Foods',
    description: 'A vegetarian burger patty with fresh veggies.',
    createdAt: DateTime.now().subtract(Duration(days: 10)),
    updatedAt: DateTime.now().subtract(Duration(days: 7)),
  ),
  Item(
    name: 'Cola Classic',
    stockCount: 50,
    category: 'Beverages',
    description: 'The classic cola flavor.',
    createdAt: DateTime.now().subtract(Duration(days: 2)),
    updatedAt: DateTime.now().subtract(Duration(days: 2)),
  ),
  Item(
    name: 'Diet Cola',
    stockCount: 35,
    category: 'Beverages',
    description: 'Cola with zero sugar.',
    createdAt: DateTime.now().subtract(Duration(days: 8)),
    updatedAt: DateTime.now().subtract(Duration(days: 5)),
  ),
  Item(
    name: 'Vanilla Ice Cream',
    stockCount: 20,
    category: 'Desserts',
    description: 'Creamy vanilla flavored ice cream.',
    createdAt: DateTime.now().subtract(Duration(days: 5)),
    updatedAt: DateTime.now().subtract(Duration(days: 4)),
  ),
  Item(
    name: 'Chocolate Ice Cream',
    stockCount: 18,
    category: 'Desserts',
    description: 'Rich chocolate flavored ice cream.',
    createdAt: DateTime.now().subtract(Duration(days: 12)),
    updatedAt: DateTime.now().subtract(Duration(days: 6)),
  ),
  Item(
    name: 'Strawberry Ice Cream',
    stockCount: 15,
    category: 'Desserts',
    description: 'Sweet strawberry flavored ice cream.',
    createdAt: DateTime.now().subtract(Duration(days: 15)),
    updatedAt: DateTime.now().subtract(Duration(days: 12)),
  ),
    Item(
    name: 'Classic Burger',
    stockCount: 25,
    category: 'Foods',
    description: 'A burger with lettuce, tomato, and cheese.',
    createdAt: DateTime.now().subtract(Duration(days: 3)),
    updatedAt: DateTime.now().subtract(Duration(days: 1)),
  ),
  Item(
    name: 'Cheeseburger',
    stockCount: 30,
    category: 'Foods',
    description: 'A burger topped with melted cheese.',
    createdAt: DateTime.now().subtract(Duration(days: 6)),
    updatedAt: DateTime.now().subtract(Duration(days: 2)),
  ),
  Item(
    name: 'Chicken Burger',
    stockCount: 15,
    category: 'Foods',
    description: 'A burger with a crispy chicken patty.',
    createdAt: DateTime.now().subtract(Duration(days: 7)),
    updatedAt: DateTime.now().subtract(Duration(days: 4)),
  ),
  Item(
    name: 'Veggie Burger',
    stockCount: 10,
    category: 'Foods',
    description: 'A vegetarian burger patty with fresh veggies.',
    createdAt: DateTime.now().subtract(Duration(days: 10)),
    updatedAt: DateTime.now().subtract(Duration(days: 7)),
  ),
  Item(
    name: 'Cola Classic',
    stockCount: 50,
    category: 'Beverages',
    description: 'The classic cola flavor.',
    createdAt: DateTime.now().subtract(Duration(days: 2)),
    updatedAt: DateTime.now().subtract(Duration(days: 2)),
  ),
  Item(
    name: 'Diet Cola',
    stockCount: 35,
    category: 'Beverages',
    description: 'Cola with zero sugar.',
    createdAt: DateTime.now().subtract(Duration(days: 8)),
    updatedAt: DateTime.now().subtract(Duration(days: 5)),
  ),
  Item(
    name: 'Vanilla Ice Cream',
    stockCount: 20,
    category: 'Desserts',
    description: 'Creamy vanilla flavored ice cream.',
    createdAt: DateTime.now().subtract(Duration(days: 5)),
    updatedAt: DateTime.now().subtract(Duration(days: 4)),
  ),
  Item(
    name: 'Chocolate Ice Cream',
    stockCount: 18,
    category: 'Desserts',
    description: 'Rich chocolate flavored ice cream.',
    createdAt: DateTime.now().subtract(Duration(days: 12)),
    updatedAt: DateTime.now().subtract(Duration(days: 6)),
  ),
  Item(
    name: 'Strawberry Ice Cream',
    stockCount: 15,
    category: 'Desserts',
    description: 'Sweet strawberry flavored ice cream.',
    createdAt: DateTime.now().subtract(Duration(days: 15)),
    updatedAt: DateTime.now().subtract(Duration(days: 12)),
  ),
];
