// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCspC_z5lN2fL2eVdKZiyQUZ2iXIO1S7GI',
    appId: '1:994432209140:web:4b39075b154bf544a80ea1',
    messagingSenderId: '994432209140',
    projectId: 'restaurant-talks',
    authDomain: 'restaurant-talks.firebaseapp.com',
    storageBucket: 'restaurant-talks.appspot.com',
    measurementId: 'G-464TTK30MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX_973WRqT028Q2jbEB9HNoTTQlqfT2SE',
    appId: '1:994432209140:android:81739176570f7f56a80ea1',
    messagingSenderId: '994432209140',
    projectId: 'restaurant-talks',
    storageBucket: 'restaurant-talks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7DBwXAA5HdJc8jN4-PxKy4yBfsxbIPzQ',
    appId: '1:994432209140:ios:2df8b7028a2ebbfaa80ea1',
    messagingSenderId: '994432209140',
    projectId: 'restaurant-talks',
    storageBucket: 'restaurant-talks.appspot.com',
    iosClientId: '994432209140-4ikm65nhftjor9c3at53g99gs3t7ikqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantTalks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7DBwXAA5HdJc8jN4-PxKy4yBfsxbIPzQ',
    appId: '1:994432209140:ios:e5f03a7eff39a399a80ea1',
    messagingSenderId: '994432209140',
    projectId: 'restaurant-talks',
    storageBucket: 'restaurant-talks.appspot.com',
    iosClientId: '994432209140-72002o9r80tbfvd87ed6vj0hjcbv8q8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantTalks.RunnerTests',
  );
}
